# ?? ??
server:
  port: 8000

spring:
  datasource:
    # ?????? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # mysql
    username: root
    password: dlscjs1@34
  # ?? ??
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      #?? ??
  http:
    encoding:
      charset: UTF-8
      enabled: true
  mvc:
    charset: UTF-8


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

